# Generated by Django 4.2.5 on 2023-10-14 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('D', 'Dañado')], default='Nuevo', max_length=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
