# Generated by Django 4.2.5 on 2023-10-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='estado',
            field=models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('D', 'Dañado')], default='N', max_length=1),
        ),
    ]
