# Generated by Django 4.2.5 on 2023-10-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0002_alter_donacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Dañado')], default=1),
        ),
    ]
