# Generated by Django 4.2.5 on 2023-10-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0003_alter_donacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
    ]
