# Generated by Django 4.2.30 on 2026-04-28 21:45

from django.db import migrations

import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', usuarios.models.CustomUserManager()),
            ],
        ),
    ]
